# Generated by Django 3.2.8 on 2021-12-03 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211127_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_application', models.BooleanField(default=False)),
                ('Instructor_application', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('m_initial', models.CharField(max_length=1, null=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('birth_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('phone_number', models.IntegerField(default=0)),
                ('street_address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=2)),
                ('zip_code', models.IntegerField(default=0)),
                ('sc_name', models.CharField(max_length=50, null=True)),
                ('sc_city', models.CharField(max_length=50, null=True)),
                ('sc_state', models.CharField(max_length=2, null=True)),
                ('graduation_date', models.DateField(null=True)),
                ('gpa', models.FloatField(null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('status_pending', models.BooleanField(default=True)),
                ('status_approved', models.BooleanField(default=False)),
                ('status_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='m_initial',
            field=models.CharField(default='', max_length=1),
        ),
    ]
