# Generated by Django 3.2.8 on 2021-11-13 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211112_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
