# Generated by Django 3.2.8 on 2021-11-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211112_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sc_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sc_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sc_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='m_initial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
