# Generated by Django 3.2.8 on 2021-12-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211203_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
