# Generated by Django 3.2.8 on 2021-12-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
        ('users', '0005_auto_20211205_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='graduation.graduatingclass'),
        ),
    ]
