# Generated by Django 3.2.8 on 2021-12-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name_plural': 'Reports'},
        ),
    ]
