# Generated by Django 3.2.8 on 2021-12-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20211207_1317'),
        ('users', '0008_merge_20211207_1318'),
    ]

    operations = [
    ]
