# Generated by Django 3.2.8 on 2021-12-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20211208_2315'),
        ('users', '0010_auto_20211209_0225'),
    ]

    operations = [
    ]
