# Generated by Django 3.2.8 on 2021-12-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20211209_0335'),
        ('users', '0011_merge_20211209_0339'),
    ]

    operations = [
    ]
