# Generated by Django 3.2.8 on 2021-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='CourseDescription',
        ),
    ]
