# Generated by Django 3.2.8 on 2021-11-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211119_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'classes'},
        ),
    ]
