# Generated by Django 3.2.8 on 2021-11-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211127_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takencourse',
            options={'verbose_name_plural': 'TakenCourses'},
        ),
    ]
