# Generated by Django 3.2.8 on 2021-12-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_reviewclasses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='current_capacity',
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reviewclasses',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
