# Generated by Django 3.2.8 on 2021-12-06 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_reviewclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='class_set_up_period',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 19, 55, 43, 802056)),
        ),
    ]
