# Generated by Django 3.2.8 on 2021-12-06 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_session_class_set_up_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='class_set_up_period',
        ),
        migrations.AddField(
            model_name='session',
            name='class_running_period_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='class_running_period_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='class_set_up_period_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='class_set_up_period_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='course_registration_period_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='course_registration_period_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='grading_period_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
        migrations.AddField(
            model_name='session',
            name='grading_period_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 20, 52, 54, 225551)),
        ),
    ]
