# Generated by Django 3.2.8 on 2021-12-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20211206_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='days_and_time',
        ),
    ]
