# Generated by Django 3.2.8 on 2021-12-06 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20211205_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='class_running_period_end',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='session',
            name='class_set_up_period_end',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='session',
            name='course_registration_period_end',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='session',
            name='grading_period_end',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 23, 59, 59)),
        ),
    ]
