# Generated by Django 3.2.8 on 2021-12-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_warningcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningcount',
            name='count',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
