# Generated by Django 3.2.8 on 2021-12-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20211205_2236'),
        ('courses', '0017_alter_warningcount_count'),
    ]

    operations = [
    ]
