# Generated by Django 3.2.9 on 2021-12-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_classes_class_id'),
        ('courses', '0018_merge_20211207_1318'),
    ]

    operations = [
    ]
