# Generated by Django 3.2.8 on 2021-12-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20211207_1317'),
        ('courses', '0020_alter_classes_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
    ]
