# Generated by Django 3.2.8 on 2021-12-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_merge_20211208_1643'),
        ('courses', '0021_waitlist_instructor'),
    ]

    operations = [
    ]
