# Generated by Django 3.2.8 on 2021-12-09 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_merge_20211209_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classes',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.session'),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
    ]
