# Generated by Django 3.2.8 on 2021-12-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_merge_20211208_2316'),
        ('courses', '0023_auto_20211209_0050'),
    ]

    operations = [
    ]
