# Generated by Django 3.2.8 on 2021-12-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_session_curreent_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='curreent_period',
            new_name='current_period',
        ),
    ]
