# Generated by Django 3.2.8 on 2021-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_session_current_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclasses',
            name='non_censored',
            field=models.TextField(null=True),
        ),
    ]
