# Generated by Django 3.2.8 on 2021-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_merge_0023_auto_20211209_0050_0025_automaticwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclasses',
            name='non_censored',
            field=models.TextField(null=True),
        ),
    ]
