# Generated by Django 3.2.8 on 2021-12-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_reviewclasses_non_censored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('W', 'W')], max_length=1),
        ),
    ]
