# Generated by Django 3.2.8 on 2021-12-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warningsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warnings',
            name='registrar',
        ),
        migrations.RemoveField(
            model_name='warnings',
            name='user',
        ),
    ]
