# Generated by Django 3.2.8 on 2021-12-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_merge_20211207_1318'),
        ('warningsystem', '0002_auto_20211208_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='registrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registrar'),
        ),
        migrations.AddField(
            model_name='warnings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
