# Generated by Django 3.2.8 on 2021-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warningsystem', '0003_auto_20211208_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
