# Generated by Django 3.2.8 on 2021-12-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warningsystem', '0004_alter_warnings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
