# Generated by Django 3.2.8 on 2021-12-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0016_auto_20211205_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
            ],
        ),
    ]
