# Generated by Django 3.2.8 on 2021-12-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_graduation_class'),
        ('graduation', '0002_alter_graduatingclass_graduation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.graduatingclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
