# Generated by Django 3.2.8 on 2021-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0003_graduationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graduationapplication',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graduationapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
